name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Admin dependencies
      working-directory: admin
      run: npm install

    - name: Install Frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build Frontend
      working-directory: frontend
      run: npm run build

    - name: Install Backend dependencies
      working-directory: backend
      run: npm install

    - name: Echo success
      run: echo "✅ Build pipeline completed successfully"
